print("")

import os
os.system('pip3 install google')
os.system('pip3 install colorama')
os.system('apt install wget')
os.system('pip3 install wget')
os.system('pip3 install requests')
os.system('pip3 install sockets')
os.system('pip3 install pythonping')
os.system('pip3 install os-sys')
os.system('pip3 install times')
os.system('pip3 install sys')
os.system('pip3 install ipaddress')
os.system('pip3 install pyexiftool')
os.system('pip3 install beautifulsoup4')
os.system('pip3 install phonenumbers')
os.system('pip3 install faker')
os.system('pip3 install urllib3')
os.system('pip3 install regex')
os.system('pip3 install argparse')
os.system('pip3 install random2')
os.system('pip3 install openai')
os.system('pip3 install importlib')
os.system('pip3 install scapy')
